services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: frog_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 3s
      timeout: 3s
      retries: 5

  # frogshort:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frogshort
  #   container_name: frogshort
  #   env_file: .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped

  migrate:
    image: postgres:16
    container_name: frog_db_migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASS}
      PGDATABASE: ${DB_NAME}
      PGHOST: db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/migrations/run-migrations.sh"]
    restart: "no"
volumes:
  db_data: